### **1. Identifying missing values in tabular data.**

In [1]:
import pandas as pd
from io import StringIO

csv_data = \
  '''A,B,C,D
  1.0,2.0,3.0,4.0
  5.0,6.0,,8.0
  10.0,11.0,12.0,'''

df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [2]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [3]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [4]:
# access the underlying NumPy array of a DataFrame
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

### **2. Eliminating training examples or features with missing values**

In [5]:
# drop rows with missing values.
df.dropna(axis=0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [6]:
# drop columns that have at least one NaN in any row

df.dropna(axis=1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [7]:
# only drop rows where all columns are NaN
df.dropna(how='all')

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [8]:
# drop rows that have fewer than 4 real values
df.dropna(thresh=4)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [9]:
# only drop rows where NaN appear in specific columns
df.dropna(subset=['C'])

      A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

### **3. Imputing missing values**

- Deleting rows or columns with missing data often results in losing too much valuable information for a model to learn effectively.

- Interpolation techniques allow us to fill in those gaps using the remaining dataset.

- **Mean Imputation** is the most common method, where missing entries in a column are replaced by the average (mean) of all other values in that same column.

- Documentation: https://scikit-learn.org/stable/modules/impute.html.

In [10]:
from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)

imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [11]:
df.fillna(df.mean())

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.5  8.0
2  10.0  11.0  12.0  6.0